//此js放置全局常量

let CC_USERNAME ='userName';
let CC_IDCARD='idCard';
let CC_AUTHORIZESTATUS ='authorizeStatus';
let CC_DEVICEID ='deviceId';
let CC_AREAID ='areaId';
let CC_FARMERID='farmerId';
let CC_ACCOUNTNAME ='accountName';
let CC_ADDRESS ='address';
let CC_BANKADDRESS ='bankAddress';
let CC_BANKADDRESSNAME ='bankAddressName';
let CC_BANKCODE ='bankCode';
let CC_BANKNAME ='bankName';
let CC_BANKNUMBER ='bankNumber';
let CC_DESCRIPTION_EVALUATE ='descriptionEvaluate';
let CC_LEADER_ID ='leaderId';
let CC_MANAGER_NAME ='managerName';
let CC_MGRID ='mgrid';
let CC_MOBILE ='mobile';
let CC_PERSONTYPE ='personType';
let CC_PICPATH ='picPath';
let CC_SEND_ADDRESS_NAME ='sendAddressName';
let CC_SERVICEEVALUATE ='serviceEvaluate';
let CC_SHIP_EVALUATE ='shipEvaluate';
let CC_STORE_EVALUATE ='storeEvaluate';
let CC_SEX ='sex';
let CC_USERTYPE ='userType';
let CC_FARMERINFO ='farmerinfo';
let CC_OPENID='openId';
let CC_WEIXININFO='weixininfo';
let CC_GOODINFOLIST = 'goodInfoList';
let CC_SHIPINFOLIST = 'shipInfoList';
let CC_MESSAGELIST = 'messageList';
/** 头像 */
let CC_PHOTO_TYPE_HEAD_IMG = 1;
/** 认证 */
let CC_PHOTO_TYPE_CERTIFY = 2;
/** 种植地 */
let CC_PHOTO_TYPE_LAND_TYPE = 3;
/** 产品主图 */
let CC_PHOTO_TYPE_PRODUCT_MAIN = 8;
/** 商品列表 */
let CC_PHOTO_TYPE_PRODUCT_LIST = 5;




exports.CC_USERNAME = CC_USERNAME;
exports.CC_IDCARD = CC_IDCARD;
exports.CC_FARMERID = CC_FARMERID;
exports.CC_AUTHORIZESTATUS = CC_AUTHORIZESTATUS;
exports.CC_DEVICEID = CC_DEVICEID;
exports.CC_AREAID = CC_AREAID;
exports.CC_FARMERID = CC_FARMERID;
exports.CC_ACCOUNTNAME = CC_ACCOUNTNAME;
exports.CC_ADDRESS = CC_ADDRESS;
exports.CC_BANKADDRESS = CC_BANKADDRESS;
exports.CC_BANKADDRESSNAME = CC_BANKADDRESSNAME;
exports.CC_BANKCODE = CC_BANKCODE;
exports.CC_BANKNAME = CC_BANKNAME;
exports.CC_BANKNUMBER = CC_BANKNUMBER;
exports.CC_DESCRIPTION_EVALUATE = CC_DESCRIPTION_EVALUATE;
exports.CC_LEADER_ID = CC_LEADER_ID;
exports.CC_MANAGER_NAME = CC_MANAGER_NAME;
exports.CC_MGRID = CC_MGRID;
exports.CC_MOBILE = CC_MOBILE;
exports.CC_PERSONTYPE = CC_PERSONTYPE;
exports.CC_PICPATH = CC_PICPATH;
exports.CC_SEND_ADDRESS_NAME = CC_SEND_ADDRESS_NAME;
exports.CC_SERVICEEVALUATE = CC_SERVICEEVALUATE;
exports.CC_SHIP_EVALUATE = CC_SHIP_EVALUATE;
exports.CC_STORE_EVALUATE = CC_STORE_EVALUATE;
exports.CC_SEX = CC_SEX;
exports.CC_USERTYPE = CC_USERTYPE;
exports.CC_FARMERINFO = CC_FARMERINFO;
exports.CC_OPENID = CC_OPENID;
exports.CC_WEIXININFO = CC_WEIXININFO;
exports.CC_GOODINFOLIST = CC_GOODINFOLIST;
exports.CC_SHIPINFOLIST = CC_SHIPINFOLIST;
exports.CC_PHOTO_TYPE_HEAD_IMG = CC_PHOTO_TYPE_HEAD_IMG;
exports.CC_PHOTO_TYPE_CERTIFY = CC_PHOTO_TYPE_CERTIFY;
exports.CC_PHOTO_TYPE_LAND_TYPE = CC_PHOTO_TYPE_LAND_TYPE;
exports.CC_PHOTO_TYPE_PRODUCT_MAIN = CC_PHOTO_TYPE_PRODUCT_MAIN;
exports.CC_PHOTO_TYPE_PRODUCT_LIST = CC_PHOTO_TYPE_PRODUCT_LIST;
exports.CC_MESSAGELIST = CC_MESSAGELIST;

